import { Inter } from "next/font/google";
import "./globals.css";
import dynamic from "next/dynamic";
import { Toaster } from "react-hot-toast";
import Navbar from "./components/navbar";
import Footer from "./components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Online Divorce",
  description: "Generated by create next app",
};

const NextProgress = dynamic(() => import("@/app/components/NextProgress"), {
  ssr: false,
});

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NextProgress />
        <Navbar />
        {children}
        <div className="p-4">
          <Footer />
        </div>
        <Toaster position="top-center" />
      </body>
    </html>
  );
}
